version: '3.9'

services:
  be:
    container_name: PCompilerBE
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    command: sh -c "poetry run uvicorn index:app --reload --host 0.0.0.0 --port 8000"
    networks:
      - pcompiler

  web:
    container_name: PCompilerWeb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_URL: "http://localhost:8000/api/py"
      NEXT_PUBLIC_ELECTRON: false
    networks:
      - pcompiler

networks:
  pcompiler:
    driver: bridge
