version: '3.9'

services:
  be:
    container_name: PCompilerBE
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "2604:2604"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      FORWARDED_ALLOW_IPS: "*"
    command: sh -c "poetry run uvicorn index:app --reload --host 0.0.0.0 --port 2604"
    networks:
      - pcompiler

  web:
    container_name: PCompilerWeb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_URL: "http://116.118.51.244:2604/api/py"
      NEXT_PUBLIC_ELECTRON: false
    networks:
      - pcompiler

  nginx:
    depends_on:
      - web
      - be
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pcompiler

networks:
  pcompiler:
    driver: bridge
